### PR TITLE
add Brooklyn Plugin

### PR DESCRIPTION
**Pull request by robertgmoss**

### CODE REVIEW

**Comment by robertgmoss** [comment]
send CLA by email

**Comment by simonleung8** [comment]
@robertgmoss Thanks for the plugin.
Because of how the commands are namespaced `cf brooklyn <command>`, the help won't be properly displayed. `cf brooklyn login -h` will just return the help for command brooklyn. In order for the help to be displayed, the commands will have to in args[0], for example, `cf brooklyn-login`, `cf brooklyn-push`.

**Comment by goehmen** [comment]
@robertgmoss Two things:

1.  To clarify Simon's comment above - You can opt to do nothing and those commands won't have a callable help associated with them or you can change the command names as suggested to enable the invocation of help for them.  We are waiting to hear which you want to go with. 

2.  For the brooklyn command itself, it says typing `cf brooklyn` will show help:  "Brooklyn plugin command's help text" but typing `cf brooklyn` actually returns 
`runtime error: index out of range` because the CLI is looking for the next argument which it expects you to supply on cmdline.

You've got the CF CLI team hear to help so let us know what we can do.

**Comment by robertgmoss** [comment]
Thanks.  This is a good reminder that I need to sort the help out.

I was thinking of implementing the help command in the plugin. I think it would be nicer than changing all the commands to brooklyn-*, especially for push.

**Comment by robertgmoss** [comment]
hopefully this is acceptable now

**Comment by simonleung8** [comment]
Thanks, looks good. Merged!

**Pull request merged**
