### PR TITLE
add cf-doctor-plugin

### PR DESCRIPTION
**Pull request by emirozer**

### CODE REVIEW

**Comment by krishicks** [comment]
Hi @emirozer,

In the previous PR it looked like you renamed this plugin command from 'anomaly' to 'doctor', but the description still says 'anomaly'. Is that correct?

**Comment by emirozer** [comment]
Hey @krishicks 

Haha, i tried to mean ,  {this plugin} anomaly scans in your cf cluster (CLI v6.7.0+)

I guess it can be confusing, let me be more clear in the description

**Comment by dkoper** [comment]
I was just wondering, what do you mean by 'cf cluster ' ? I don't think that terminology is used in any of our documentation. Sounds like this plugin is to be used with a special CF distribution or cluster supporting plugin that should be mentioned here?

**Comment by emirozer** [comment]
Yeah you have point @dkoper , cf instance should be a better term i guess ? what's your opinion

**Comment by dkoper** [comment]
With just cf (or cf instance), I'd interpret it to mean the plugin's target audience is for operators to detect issues with their CF installation?
Why not just say what it does? E.g. `doctor scans your deployed applications and routes for anomalies and reports any issues found.`. In subsequent versions you can expand on that, e.g. `doctor scans your deployed applications, routes and service instances for anomalies and reports any issues found with suggested remedies.`

**Comment by emirozer** [comment]
@dkoper thank you!, that description is better, i agree..

Updated and ammended

**Comment by simonleung8** [comment]
@emirozer Thanks for sharing the plugin. However, the checksum of the binaries are not correct. We are looking for the SHA-1 checksum. For example, the SHA1 checksum for your OSX binary would be "816c1e3e34be40e5495b766285c9be2416d57233"

Thanks

**Comment by emirozer** [comment]
@simonleung8 i did md5 instead SHA1, thanks for the headsup, fixed now

**Pull request merged**
