### PR TITLE
added new plugin to repo-index.yml / cf doctor plugin

### PR DESCRIPTION
**Pull request by emirozer**
Hi,

Do let me know if something is missing.. I only found out that i need to update repo-index.yml file and thats it..

Thanks!

### CODE REVIEW

**Comment by emirozer** [comment]
Please do not merge this yet.. There is a small bug, going to fix it and give OK here, thanks!

**Comment by emirozer** [comment]
Yes, good to merge :)

**Comment by krishicks** [comment]
Hi @emirozer,

Could you squash these commits into one?

**Comment by emirozer** [comment]
-.- i accidentally squashed an extra commit and changed the history of my fork.. its better if i close this and open a new pr.. i am sorry about this..

**Pull request closed without merging**
