### PR TITLE
Add Spring Cloud Services plugin

### PR DESCRIPTION
**Pull request by glyn**

### CODE REVIEW

**Comment by glyn** [comment]
Raised https://github.com/cloudfoundry-incubator/cli-plugin-repo/issues/179 to ensure the travis failure is addressed, independently of this PR.

**Comment by dkoper** [comment]
I have resolved the issue with the other plugin. A test is still failing.
Did you run `go run sort/main.go repo-index.yml` to sort your additions to the file?

**Comment by glyn** [comment]
@dkoper Doh! No, sorry, I missed that completely. Will fix later today.

**Comment by glyn** [comment]
@dkoper Sorted the index. Please proceed.

**Comment by dkoper** [comment]
Thanks!
Sorting is a recent requirement: allows easier automation of publishing of plugin updates.

**Pull request merged**
