### PR TITLE
Add cf-predix-analytics-plugin

### PR DESCRIPTION
**Pull request by nobodyzzz**

### CODE REVIEW

**Comment by dkoper** [comment]
@nobodyzzz Looks good, waiting for the OK from the CFF when they receive your CLA.

**Comment by nobodyzzz** [comment]
@dkoper AFAIK Altros has already signed CLA

**Comment by dkoper** [comment]
@nobodyzzz Please change your GitHub profile settings to make your membership of the Altoros organization public.

**Comment by chipchilders** [comment]
Closing / re-opening to check CLA

**Comment by chipchilders** [comment]
Closing / re-opening to check CLA

**Pull request merged**
