### PR TITLE
added started-apps plugin

### PR DESCRIPTION
**Pull request by mgwebb**

### CODE REVIEW

**Comment by dkoper** [comment]
Please take a look at the comment from the bot above. We can merge when that's resolved.

**Comment by mgwebb** [comment]
Cloud Foundry Org has processed my CLA - is there anything else I need to do?

Thanks,
Mark Webb
________________________________

**Comment by dkoper** [comment]
@chipchilders Can you confirm?

**Comment by chipchilders** [comment]
@dkoper open / close the PR to get the bot to re-check (doing so now)

**Comment by chipchilders** [comment]
opening again

**Comment by dkoper** [comment]
Thanks!

**Pull request merged**
