### PR TITLE
New plugin named "copy"

### PR DESCRIPTION
**Pull request by mevansam**
Project: https://github.com/mevansam
CI: https://app.wercker.com/mevansam/cf-copy-plugin

### CODE REVIEW

**Comment by dkoper** [comment]
@mevansam please make your GitHub organisation membership public if this contribution is covered under a CCLA signatory, and resolve the conflicts.

**Comment by mevansam** [comment]
Hi @dkoper: My GitHub public profile has been updated and I have also verified that all checks have passed for the repo-index.yml. Thanks.

**Comment by dkoper** [comment]
re-opening to let cla bot kick in again

**Comment by dkoper** [comment]
@mevansam Do you mind squashing your commits into one?

**Comment by mevansam** [comment]
I've completely messed up my fork. I need to delete that fork and create a new one with the valid repo-index.yml metadata for the "copy" plugin. I will submit a new pull request from there. So I am going to close this request.

**Pull request closed without merging**
