### PR TITLE
Bumped cf-plugin-deploy for v0.2.0

### PR DESCRIPTION
**Pull request by geofffranks**

### CODE REVIEW

**Comment by dkoper** [comment]
@geofffranks Any particular reason for not bumping the version and updated fields?
```
  version: 0.1.1
  updated: 2017-04-18T00:00:00Z
```

**Comment by geofffranks** [comment]
Totally missed those. Will fix and resubmit. Thanks!

**Comment by dkoper** [comment]
@geofffranks Feel free to add a commit to this PR, or even merge it into your current commit.

**Comment by geofffranks** [comment]
@dkoper Fixed, sorry for the delay

**Comment by dkoper** [comment]
Thanks!

**Pull request merged**
