### PR TITLE
add kibana-me-logs v0.2.1

### PR DESCRIPTION
**Pull request by drnic**
kibana-me-logs plugin release ~~v0.1.0~~ ~~v0.2.0~~ v0.2.1

### CODE REVIEW

**Comment by drnic** [comment]
Two days has gone by. This model of sharing plugins probably isn't going to work if it takes hours or days before it shows up and ppl can use the plugin.

Thoughts on a new solution going forward? Perhaps can we put the index file into a new repo that automatically accepts PRs, and auto-deploys the app?

**Comment by drnic** [comment]
And given the mistakes I've just realised I've made in my PR, I guess we need some automated verification system :)

**Comment by drnic** [comment]
PR fixed.

```
$ cf install-plugin kibana-me-logs -r local-repo
Looking up 'kibana-me-logs' from repository 'local-repo'
8143892 bytes downloaded...
Installing plugin /var/folders/3x/fch8r6z97ljct1tfzk7kk34w0000gn/T/ filename=cf-plugin-kibana-me-logs_darwin_amd64...
OK
```

**Comment by simonleung8** [comment]
@drnic The binaries for Windows 32 and Linux 32 seems to be not there, can you update?

**Comment by drnic** [comment]
Ahh thanks for spotting that. I didn't update my release.sh script for the 32b uploads https://github.com/cloudfoundry-community/cf-plugin-kibana-me-logs/blob/master/bin/release.sh#L28

Will upload soon

**Comment by drnic** [comment]
Ok, new 32-bit versions also uploaded.

**Comment by drnic** [comment]
Thanks!

**Comment by simonleung8** [comment]
thanks, merged

**Pull request merged**
