### PR TITLE
Adding CopyEnv Plugin - Update repo-index.yml

### PR DESCRIPTION
**Pull request by jthomas**

### CODE REVIEW

**Comment by jthomas** [comment]
I'm an IBMer, I'll go and check who I can talk to so that I can get added to our corporate CLA.

**Comment by christo4ferris** [comment]
I have added James to cfibmers. This PR may be merged once approved.

**Comment by jthomas** [comment]
Added test coverage to the plugin as requested. 
Updated links to new plugin binaries.

**Comment by simonleung8** [comment]
Thanks and merged

**Comment by jthomas** [comment]
:100:

**Pull request merged**
