### PR TITLE
Minor bug fixes and enhancements with fixed yml

### PR DESCRIPTION
**Pull request by kkellner**

### CODE REVIEW

**Comment by dkoper** [comment]
Thanks!
Description is not rendering well on the plugin site though..

**Comment by kkellner** [comment]
I noticed that.   I wasn't sure if markup would work (e.g., prefixing list items with "*").   If you have suggestion for future updates to format output nicer, let me know.

**Comment by dkoper** [comment]
Will ask the team...

**Comment by kkellner** [comment]
I entended the output to look something like this:

- Fixed: AppDetailView is now refreshed in background while the App Info view is displayed.
- Fixed: When viewing appListDetail view the header toggle (shift-h) would also collapse Http and Crash data boxes. This has been fixed to only collapse verbose header output.
- Fixed: Use LogMessage timestamp instead of Event timestamp for tracking last container messages.
- Fixed: Highlight scrolling and display list issue fixed when the list of data becomes smaller then the current scrolling offset.

- Fixed: Issue with terminal window with zero dimension causing panic because helpTextTipsView layout error:invalid dimensions.
- Enhancement: Save column filter for each view type allowing easier usage when returning back to a view that has customized column filters.
- Enhancement: Save column sort order for each view type allowing easier usage when returning back to a view that has customized column sorts.
- Enhancement: Monitor staging events to reload metadata when staging is complete.
- Enhancement: Added Clipboard menu option to appDetailView.

**Comment by dkoper** [comment]
@kkellner We found a way! See https://github.com/cloudfoundry-incubator/cli-plugin-repo/commit/a08c4dbd7677119add08cf6f5e55a7ac179ce7ae.

**Comment by kkellner** [comment]
Great!  Thanks for finding a solution.

**Pull request merged**
