### PR TITLE
Added cf-console and cf-live-stats

### PR DESCRIPTION
**Pull request by danhigham**
Two plugins;

D3 Live Stats :- https://github.com/danhigham/cf-live-stats

Console :- https://github.com/danhigham/cf-console

### CODE REVIEW

**Comment by ragaskar** [comment]
This pull revealed a bug in the CLI repo -- the app should coerce the version value to a string (right now, it thinks the `version: 1.0` is a float and blows up on a type error). Story here: https://www.pivotaltracker.com/story/show/88820854

**Comment by simonleung8** [comment]
@danhigham The linux64 binary link to Console is not working, otherwise it looks great.
Can you update the link. Thanks

**Comment by danhigham** [comment]
Done :-)

**Comment by simonleung8** [comment]
Thanks, merged =)

**Pull request merged**
