### PR TITLE
Update cf-download Fixed

### PR DESCRIPTION
**Pull request by reSoley**
Fixed pull request #83 

I'm a member of the cfibmers org now which should have a CLA on file. Also, I fixed the checksums. I had flipped the Win64 and Linux ones.

### CODE REVIEW

**Comment by dkoper** [comment]
@reSoley Is there any particular reason you're not bumping the version and updated fields?
We have a story coming up for the cf CLI to list out if date plugins. It won't detect your updates if you only change the checksums.
Also, have you considered using a GitHub 'release' instead of just saving your binaries in your source repo? If you update the binaries in place (I.e. Same URL when you update them), suddenly the checksums in this file become incorrect until we can merge your PR. And during this time, the travis tests for PRs for other people's plugins fail too as the unit tests verify all fields of the yml file.

**Comment by reSoley** [comment]
@dkoper No reason, just missed those fields. I'll update them in another commit and draft a release and point the urls there.

**Comment by dkoper** [comment]
@reSoley There's a merge conflict - did you forget to rebase?

**Comment by reSoley** [comment]
@dkoper Yeah, I'll open a new pull request with rebased commits.

**Pull request closed without merging**
