### PR TITLE
v0.3.0 kibana-me-logs

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
Bump. This is a week old now. Can we please automate this? Or give more ppl commit access & deploy access to http://plugins.cfapps.io/ui/ ?

Or do we prefer that ppl run their own http://plugins.cfapps.io/ui/ ?

**Comment by drnic** [comment]
@goehmen ^

**Comment by simonleung8** [comment]
@drnic Sorry this took a while, this PR didn't create a story in the public tracker, we are investigating for the reason.
Anyway, merged.

**Comment by drnic** [comment]
Thanks mate. Does this auto trigger the app to be deployed? Or is there another tracker ticket for that?

**Comment by simonleung8** [comment]
It is the same tracker ticket. We deploy the app with new changes once the PR is merged.

**Comment by drnic** [comment]
Ok awesome thanks!

**Comment by cunnie** [comment]
@drnic @simonleung8 Our bad, there was a gitbot bug; It's now fixed.

Dr Nic: your pull request was quite odd in that the body portion was null (rather than an empty string, which is usually the case). The gitbot code didn't account for the possibility of a null body, and failed to post a story in tracker.  We re-delivered the payload to make sure the fix worked (it did), so now tracker has **two** stories w.r.t. your pull request.

**Comment by drnic** [comment]
Ahh ok I'll alway put bodies in PRs in future.

**Pull request merged**
