### PR TITLE
Add cf-aklogin

### PR DESCRIPTION
**Pull request by phedoreanu**
CF Login tool to switch between CF environments with a single command.

### CODE REVIEW

**Comment by dkoper** [comment]
@phedoreanu PR looks good. Please take a look at the comment from cf-gitbot above.

**Comment by phedoreanu** [comment]
@timjsavage?

**Comment by timjsavage** [comment]
Hi,
CLA submitted to contributors@cloudfoundry.org
Thanks!

**Comment by dkoper** [comment]
@chipchilders Can you confirm we're OK to proceed?

**Comment by chipchilders** [comment]
open / close to kick the CLA bot

**Comment by chipchilders** [comment]
open / close to kick the CLA bot

**Comment by dkoper** [comment]
Thanks!

**Pull request merged**
