### PR TITLE
Add version 1.0.0 of the CF Java Plugin

### PR DESCRIPTION
**Pull request by michele-mancioppi**

### CODE REVIEW

**Comment by michele-mancioppi** [comment]
Too early :-)

**Comment by dkoper** [comment]
There is a merge commit in your PR. Please rebase and submit only your commit.

**Comment by dkoper** [comment]
Closing. Feel free to re-open or submit a new PR with my comment addressed.

**Comment by michele-mancioppi** [comment]
Uuups, did not see the notification. I do not seem to be able to reopen the PR, so I opened https://github.com/cloudfoundry-incubator/cli-plugin-repo/pull/123 instead. Sorry for the delayed response.

**Pull request closed without merging**
